name: Deploy to VPS Root
#ejecutar al hacer push a main
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}

    steps:
      # 1. Checkout y configuración inicial
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"

      # 2. Instalar pnpm y dependencias
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile
          pnpm --filter front run build

      - name: Package deploy folder
        run: |
          # Cambiar permisos para directorios a 774 (rwxrwxr--)
          find front -type d -exec chmod 774 {} +
          find back -type d -exec chmod 774 {} +

          # Cambiar permisos para archivos a 664 (rw-rw-r--)
          find front -type f -exec chmod 664 {} +
          find back -type f -exec chmod 664 {} +

          # Cambiar permisos para archivos package.json específicos a 664
          chmod 664 back/package.json
          chmod 664 package.json

          # Comprimir las carpetas y archivos con permisos ya ajustados
          tar czf deploy.tar.gz front/dist back/package.json back/src package.json

      - name: Upload file to VPS
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.PLESK_HOST }}
          username: ${{ secrets.PLESK_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: deploy.tar.gz
          target: ${{ secrets.REMOTE_PATH }}

      - name: Extract deploy tarball, fix permissions and install npm
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.PLESK_HOST }}
          username: ${{ secrets.PLESK_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Descomprimir el tarball en la carpeta destino
            tar xzf ${{ secrets.REMOTE_PATH }}/deploy.tar.gz -C ${{ secrets.REMOTE_PATH }}
            rm ${{ secrets.REMOTE_PATH }}/deploy.tar.gz

      # 4. Trigger restart en Plesk
      - name: Trigger Plesk Restart
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PLESK_HOST }}
          username: ${{ secrets.PLESK_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            touch ${{ secrets.REMOTE_PATH }}/restart.txt
            echo "🔄 Reinicio de aplicación via restart.txt"